### ISSUE TITLE
The Ranger mini v2 not exexuting commands sent through ROS.

### ISSUE THREAD

**Issue by Saksham-Bhadani** [agilexrobotics/ugv_sdk#6]
Following the instructions, a connection was established with the hardware through the USB to CAN interface. I was able to echo the `/ranger_base_node/odom` and was getting the current values of the robot confirming the connection was established. In order to write the values for linear x and y and angular z, twist messages were sent on both ros topic
`/cmd_vel` and `/four_wheel_steering_controller/cmd_vel`.

Using the remote, the robot was switched to the CAN command mode, but the values written to the ros topics did not get executed, and there was an error message popping up on the remote screen. 

Since CAN protocol is an "open to all channels" type communication, this means the commands should have been written to the hardware, leading us to believe there might be some issue we are facing with SDK.

**Comment by lagrangeluo** [comment]
Hi,in our firmware flash into the ranger mini we choose one message to execute between remote and ros message.You are right that CAN is open to all channels and ranger mini actually get the can frame send by ros driver but ranger mini can't execute two different command so we can choose one by switching in remote controller
